classes:
- system.linux.system.repo.mos9
- system.salt.control.virt
- system.salt.control.cluster.opencontrail_analytics_cluster
- system.salt.control.cluster.opencontrail_control_cluster
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
#- system.salt.control.cluster.openstack_telemetry_cluster
#- system.salt.control.cluster.stacklight_server_cluster
#- system.salt.control.cluster.stacklight_log_cluster
#- system.salt.control.cluster.stacklight_telemetry_cluster
- cluster.sriov
parameters:
  _param:
    cluster_vip_address: ${_param:infra_compute_address}
    cluster_node01_address: ${_param:infra_compute_node01_address}
    cluster_node02_address: ${_param:infra_compute_node02_address}
    cluster_node03_address: ${_param:infra_compute_node03_address}
    keepalived_vip_interface: eth1
    keepalived_vip_virtual_router_id: 69
  virt:
    nic:
      local:
        - name: nic01
          bridge: br0
          model: virtio
  salt:
    control:
      size: #RAM 4096,8192,16384,32768,65536
      ##local production sizing
        openstack.control:
          cpu: 2
          ram: 4096
          disk_profile: small
          net_profile: local
        openstack.database:
          cpu: 2
          ram: 4096
          disk_profile: large
          net_profile: local
        openstack.message_queue:
          cpu: 2
          ram: 4096
          disk_profile: small
          net_profile: local
        openstack.telemetry:
          cpu: 8
          ram: 32768
          disk_profile: xxlarge
          net_profile: local
        openstack.proxy:
          cpu: 2
          ram: 2048
          disk_profile: small
          net_profile: local
        opencontrail.control:
          cpu: 4
          ram: 8192
          disk_profile: small
          net_profile: local
        opencontrail.analytics:
          cpu: 2
          ram: 4096
          disk_profile: large
          net_profile: local
        stacklight.log:
          cpu: 4
          ram: 8192
          disk_profile: xxlarge
          net_profile: local
        stacklight.server:
          cpu: 4
          ram: 8192
          disk_profile: small
          net_profile: local
        stacklight.telemetry:
          cpu: 4
          ram: 8192
          disk_profile: xxlarge
          net_profile: local
      cluster:
        internal:
          node:
            prx02:
              provider: kvm03.${_param:cluster_domain}
  ##FIXME
  # linux:
  #   network:
  #     interface:
  #       eth0:
  #         enabled: true
  #         type: eth
  #         proto: manual
  #       eth1:
  #         enabled: true
  #         type: eth
  #         proto: manual
  #       eth2:
  #         enabled: true
  #         type: eth
  #         proto: manual
  #       br_mgm:
  #         enabled: true
  #         proto: static
  #         type: bridge
  #         address: ${_param:deploy_address}
  #         netmask: 255.255.255.0
  #         use_interfaces:
  #         - eth0
  #       bond0:
  #         enabled: true
  #         proto: manual
  #         type: bond
  #         use_interfaces:
  #         - eth1
  #         - eth2
  #         slaves: eth1 eth2
  #         mode: active-backup
  #       br_ctl:
  #         enabled: true
  #         type: bridge
  #         proto: static
  #         address: ${_param:single_address}
  #         gateway: 10.0.174.1
  #         netmask: 255.255.254.0
  #         name_servers:
  #         - 8.8.8.8
  #         - 8.8.4.4
  #         use_interfaces:
  #         - bond0
