classes:
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.git
- system.salt.master.formula.git.foundation
- system.salt.minion.ca.salt_master
- system.reclass.storage.salt
#- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.opencontrail_analytics_cluster
- system.reclass.storage.system.opencontrail_control_cluster
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_proxy_cluster
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
#- system.reclass.storage.system.openstack_telemetry_cluster
#- system.reclass.storage.system.stacklight_log_cluster
#- system.reclass.storage.system.stacklight_monitor_cluster
#- system.reclass.storage.system.stacklight_telemetry_cluster
#- system.reclass.storage.system.openstack_compute_single
- cluster.sriov
parameters:
  _param:
    salt_master_base_environment: dev
    reclass_data_repository: "https://github.com/pjediny/sriov-testlab-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    salt_master_host: ${_param:infra_config_address}
  reclass:
    storage:
      node:
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
        openstack_compute_node01:
          name: ${_param:openstack_compute_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:openstack_compute_node01_single_address}
        openstack_compute_node02:
          name: ${_param:openstack_compute_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:openstack_compute_node02_single_address}
            opencontrail_compute_iface: eth0
        openstack_compute_node03:
          name: ${_param:openstack_compute_node03_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:openstack_compute_node03_single_address}
            opencontrail_compute_iface: eth0
        infra_compute_node02:
          name: kvm02
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.infra.kvm
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:infra_compute_node02_address}
        infra_compute_node03:
          name: kvm03
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.infra.kvm
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:infra_compute_node03_address}
